baseURL: "https://mateuszreszka.xyz/"
languageCode: 'en-us'
title: "Mateusz Reszka's Personal Blog"
theme: "mr"
copyright: "This work is not licensed."
author:
  name: 'Mateusz Reszka'
  email: 'mateusz@mateuszreszka.xyz'

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  theme_config:
    appearance: "black"
    back_home_text: "Home"

outputFormats:
  RSS:
    baseName: "index"
    mediaType: "application/rss+xml"

outputs:
  home: 
    - html
    - rss
  page: 
    - html
  section: 
    - html
    - rss

markup:
  goldmark:
    parser:
      attribute:
        block: true  # default is false
    renderer:
      unsafe: true  # default is false
  highlight:
    style: manni  # default is monokai
module:
