#!/bin/sh


host=$1
[ -z "$1" ] && echo "missing host" && exit 1

set -xe
rm -r public/
hugo
echo "Copy html page..."
rsync -crvz --no-perms --delete public/ $host:/var/www/mateuszreszka.xyz/html/

rm -r public/
hugo --config config.gemini.yml
echo "Copy gemini page..."
rsync -crvz --no-perms --delete public/ $host:/var/gemini/

#echo "Copy NGINX config..."
#rsync -rvz --no-owner nginx $host:/etc/nginx/sites-available/mateuszreszka.xyz

#ssh debian@vpn << EOF
#src=/etc/nginx/sites-available/mateuszreszka.xyz
#dest=/etc/nginx/sites-enabled/mateuszreszka.xyz
#if [ ! -f \$dest ]; then 
#    echo "Adding a new symlink..."
#    ln -s \$src \$dest
#fi
#EOF

echo "All Done!"

